# mmraz-qwen3-probe-artifact-steering-question-options-answer-vast

Direct-run Vast notebook for the Qwen steering experiment.

What it does:
- loads the latest `qwen3_4b_question_options_answer_probe_artifacts_*.npz` bundle by default,
- defaults to `explicit_train_only` + `mean_answer_tokens` + `mm_steering_vectors`,
- evaluates baseline plus steering on the expanded `explicit_test` and `implicit_full` datasets,
- uses the training-style prompt format:
  - question line,
  - `Options:` with stripped option texts,
  - `Answer:` on its own line,
- sweeps layers `10, 14, 18, 22, 26` and signed strengths `+-2, +-4, +-8, +-16, +-32`,
- keeps `do_sample=False`, and
- saves full logs, summaries, config, per-layer probe-slice stats, partial checkpoints, and heatmaps.

Important default:
- the loaded probe artifact must use the new pair-level + chat-template + no-thinking-trace format (`artifact_format_version >= 4`),
- the steering run reuses the exact held-out explicit pair indices saved in that artifact, and
- older example-level or non-chat-template probe bundles are rejected on load.

In [1]:
from pathlib import Path
import runpy

import pandas as pd
from IPython.display import display


def find_repo_root(start: Path) -> Path:
    for candidate in [start.resolve(), *start.resolve().parents]:
        if (candidate / 'pyproject.toml').exists() and (candidate / 'scripts').exists() and (candidate / 'notebooks').exists():
            return candidate
    raise RuntimeError('Could not locate repo root from current working directory.')


ROOT = find_repo_root(Path.cwd())
script_path = ROOT / 'scripts' / 'vast' / 'run_mmraz_qwen3_probe_artifact_steering.py'
script_ns = runpy.run_path(str(script_path))
run_experiment = script_ns['run_experiment']

print('Repo root   :', ROOT)
print('Helper script:', script_path)

/opt/conda/envs/my_remote_venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Repo root   : /workspace
Helper script: /workspace/scripts/vast/run_mmraz_qwen3_probe_artifact_steering.py

In [2]:
CONFIG_OVERRIDES = {
    'model_name': 'Qwen/Qwen3-4B',
    'train_regime': 'explicit_train_only',
    'feature_name': 'mean_answer_tokens',
    'vector_key': 'mm_steering_vectors',
    'layers_to_test': [10, 14, 18, 22, 26],
    'use_chat_template': True,
    'disable_thinking_trace': True,
    'strengths': [2.0, 4.0, 8.0, 16.0, 32.0],
    'pair_split_random_state': 42,
    'patch_prompt_last_only': True,
    'patch_generation_tokens': True,
    'max_new_tokens': 32,
    'quick_mode': False,
    'artifact_path': None,
    'metadata_path': None,
    'reuse_existing_results': True,
    'reuse_result_search_roots': None,
}

display(pd.DataFrame([
    {'key': key, 'value': value if not isinstance(value, list) else ', '.join(str(v) for v in value)}
    for key, value in CONFIG_OVERRIDES.items()
]))

                          key                      value
0                  model_name              Qwen/Qwen3-4B
1                train_regime        explicit_train_only
2                feature_name         mean_answer_tokens
3                  vector_key        mm_steering_vectors
4              layers_to_test         10, 14, 18, 22, 26
5           use_chat_template                       True
6      disable_thinking_trace                       True
7                   strengths  2.0, 4.0, 8.0, 16.0, 32.0
8     pair_split_random_state                         42
9      patch_prompt_last_only                       True
10    patch_generation_tokens                       True
11             max_new_tokens                         32
12                 quick_mode                      False
13              artifact_path                       None
14              metadata_path                       None
15     reuse_existing_results                       True
16  reuse_result_search_roots                       None

In [3]:
result = run_experiment(CONFIG_OVERRIDES)

Repo root: /workspace
Device: cuda
Model: Qwen/Qwen3-4B
Expanded explicit dataset: /workspace/data/raw/temporal_scope_AB_randomized/temporal_scope_explicit_expanded_500.json
Expanded implicit dataset: /workspace/data/raw/temporal_scope_AB_randomized/temporal_scope_implicit_expanded_300.json
Probe artifact: /workspace/results/qwen_question_options_answer_probe_variations_vast/20260405-185421/qwen3_4b_question_options_answer_probe_artifacts_20260405-185421.npz
Probe metadata: /workspace/results/qwen_question_options_answer_probe_variations_vast/20260405-185421/qwen3_4b_question_options_answer_probe_metadata_20260405-185421.json
Dataset source: expanded
Use chat template: True
Disable thinking trace: True
Quick mode: False
Artifact split metadata: pair_level_80_20 | version = 4
Explicit train pairs from artifact: 400
Explicit test pairs from artifact : 100 | eval subset = 100
Implicit pairs: 300 | eval subset = 300
Reuse existing results: True
Existing result search roots: ['/workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast', '/workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_colab', '/workspace/results', '/workspace/results', '/workspace']
Reusable points: 57 / 102
  explicit_test: reusable 51/51 points
  implicit_full: reusable 6/51 points

'The read operation timed out' thrown while requesting HEAD https://huggingface.co/Qwen/Qwen3-4B/resolve/main/vocab.json
Retrying in 1s [Retry 1/5].
'The read operation timed out' thrown while requesting HEAD https://huggingface.co/Qwen/Qwen3-4B/resolve/main/tokenizer.json
Retrying in 1s [Retry 1/5].
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Fetching 3 files: 100%|██████████| 3/3 [00:07<00:00,  2.42s/it]
Loading weights: 100%|██████████| 398/398 [00:03<00:00, 124.26it/s]

Loaded model | n_layers = 36 | hidden_size = 2560
A token IDs: [32, 362]
B token IDs: [33, 425]

baseline generations: 100%|██████████| 400/400 [00:00<00:00, 34129.17gen/s]

[explicit_test] reused baseline from /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_colab/20260405-194733/mmraz_qwen3_probe_artifact_steering_question_options_answer_logs_20260405-194733.csv
[implicit_full] reused baseline from /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_colab/20260405-194733/mmraz_qwen3_probe_artifact_steering_question_options_answer_logs_20260405-194733.csv
Checkpoint saved (after baseline): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
Baseline generation time (min): 0.0

steering generations:   2%|▏         | 400/20000 [00:00<00:06, 3194.96gen/s, dataset=explicit_test, layer=10, signed_strength=8]

Checkpoint saved (explicit_test-layer10-steer_long_term-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=10 strength=2 steer_long_term (reused_existing): long=0.640 imm=0.360 fallback=0.210 logprob_margin=0.6857
Checkpoint saved (explicit_test-layer10-steer_immediate-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=10 strength=2 steer_immediate (reused_existing): long=0.640 imm=0.360 fallback=0.170 logprob_margin=0.6879
Checkpoint saved (explicit_test-layer10-steer_long_term-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=10 strength=4 steer_long_term (reused_existing): long=0.650 imm=0.350 fallback=0.200 logprob_margin=0.6786
Checkpoint saved (explicit_test-layer10-steer_immediate-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=10 strength=4 steer_immediate (reused_existing): long=0.630 imm=0.370 fallback=0.190 logprob_margin=0.6786

steering generations:   3%|▎         | 600/20000 [00:00<00:06, 3194.96gen/s, dataset=explicit_test, layer=10, signed_strength=16]

Checkpoint saved (explicit_test-layer10-steer_long_term-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=10 strength=8 steer_long_term (reused_existing): long=0.670 imm=0.330 fallback=0.200 logprob_margin=0.6646
Checkpoint saved (explicit_test-layer10-steer_immediate-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=10 strength=8 steer_immediate (reused_existing): long=0.660 imm=0.340 fallback=0.140 logprob_margin=0.6406

steering generations:   4%|▍         | 900/20000 [00:00<00:07, 2626.90gen/s, dataset=explicit_test, layer=10, signed_strength=-32]

Checkpoint saved (explicit_test-layer10-steer_long_term-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=10 strength=16 steer_long_term (reused_existing): long=0.710 imm=0.290 fallback=0.230 logprob_margin=0.6584
Checkpoint saved (explicit_test-layer10-steer_immediate-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=10 strength=16 steer_immediate (reused_existing): long=0.590 imm=0.410 fallback=0.110 logprob_margin=0.5526
Checkpoint saved (explicit_test-layer10-steer_long_term-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=10 strength=32 steer_long_term (reused_existing): long=0.640 imm=0.360 fallback=0.610 logprob_margin=0.9040

steering generations:   6%|▌         | 1100/20000 [00:00<00:08, 2246.13gen/s, dataset=explicit_test, layer=14, signed_strength=2]

Checkpoint saved (explicit_test-layer10-steer_immediate-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=10 strength=32 steer_immediate (reused_existing): long=0.440 imm=0.560 fallback=0.360 logprob_margin=0.5692

steering generations:   7%|▋         | 1400/20000 [00:00<00:09, 1938.38gen/s, dataset=explicit_test, layer=14, signed_strength=-4]

Checkpoint saved (explicit_test-layer14-steer_long_term-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=14 strength=2 steer_long_term (reused_existing): long=0.640 imm=0.360 fallback=0.190 logprob_margin=0.6872
Checkpoint saved (explicit_test-layer14-steer_immediate-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=14 strength=2 steer_immediate (reused_existing): long=0.640 imm=0.360 fallback=0.180 logprob_margin=0.6947
Checkpoint saved (explicit_test-layer14-steer_long_term-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=14 strength=4 steer_long_term (reused_existing): long=0.660 imm=0.340 fallback=0.180 logprob_margin=0.6858

steering generations:   7%|▋         | 1400/20000 [00:00<00:09, 1938.38gen/s, dataset=explicit_test, layer=14, signed_strength=8]

Checkpoint saved (explicit_test-layer14-steer_immediate-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=14 strength=4 steer_immediate (reused_existing): long=0.640 imm=0.360 fallback=0.180 logprob_margin=0.7009

steering generations:   8%|▊         | 1700/20000 [00:00<00:10, 1742.37gen/s, dataset=explicit_test, layer=14, signed_strength=16]

Checkpoint saved (explicit_test-layer14-steer_long_term-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=14 strength=8 steer_long_term (reused_existing): long=0.680 imm=0.320 fallback=0.210 logprob_margin=0.6954
Checkpoint saved (explicit_test-layer14-steer_immediate-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=14 strength=8 steer_immediate (reused_existing): long=0.580 imm=0.420 fallback=0.170 logprob_margin=0.7151

steering generations:   8%|▊         | 1700/20000 [00:00<00:10, 1742.37gen/s, dataset=explicit_test, layer=14, signed_strength=-16]

Checkpoint saved (explicit_test-layer14-steer_long_term-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=14 strength=16 steer_long_term (reused_existing): long=0.700 imm=0.300 fallback=0.210 logprob_margin=0.7459

steering generations:  10%|▉         | 1900/20000 [00:01<00:11, 1600.22gen/s, dataset=explicit_test, layer=14, signed_strength=-32]

Checkpoint saved (explicit_test-layer14-steer_immediate-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=14 strength=16 steer_immediate (reused_existing): long=0.540 imm=0.460 fallback=0.070 logprob_margin=0.7277
Checkpoint saved (explicit_test-layer14-steer_long_term-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=14 strength=32 steer_long_term (reused_existing): long=0.610 imm=0.390 fallback=0.720 logprob_margin=0.8722

steering generations:  10%|█         | 2100/20000 [00:01<00:12, 1459.22gen/s, dataset=explicit_test, layer=18, signed_strength=2]

Checkpoint saved (explicit_test-layer14-steer_immediate-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=14 strength=32 steer_immediate (reused_existing): long=0.470 imm=0.530 fallback=0.430 logprob_margin=0.4822

steering generations:  12%|█▏        | 2300/20000 [00:01<00:13, 1319.24gen/s, dataset=explicit_test, layer=18, signed_strength=4]

Checkpoint saved (explicit_test-layer18-steer_long_term-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=18 strength=2 steer_long_term (reused_existing): long=0.650 imm=0.350 fallback=0.170 logprob_margin=0.6960
Checkpoint saved (explicit_test-layer18-steer_immediate-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=18 strength=2 steer_immediate (reused_existing): long=0.620 imm=0.380 fallback=0.150 logprob_margin=0.6842

steering generations:  12%|█▏        | 2300/20000 [00:01<00:13, 1319.24gen/s, dataset=explicit_test, layer=18, signed_strength=-4]

Checkpoint saved (explicit_test-layer18-steer_long_term-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=18 strength=4 steer_long_term (reused_existing): long=0.680 imm=0.320 fallback=0.170 logprob_margin=0.7039

steering generations:  12%|█▎        | 2500/20000 [00:01<00:14, 1196.92gen/s, dataset=explicit_test, layer=18, signed_strength=8]

Checkpoint saved (explicit_test-layer18-steer_immediate-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=18 strength=4 steer_immediate (reused_existing): long=0.570 imm=0.430 fallback=0.180 logprob_margin=0.6795

steering generations:  12%|█▎        | 2500/20000 [00:01<00:14, 1196.92gen/s, dataset=explicit_test, layer=18, signed_strength=-8]

Checkpoint saved (explicit_test-layer18-steer_long_term-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=18 strength=8 steer_long_term (reused_existing): long=0.710 imm=0.290 fallback=0.140 logprob_margin=0.7237

steering generations:  14%|█▎        | 2700/20000 [00:01<00:15, 1093.90gen/s, dataset=explicit_test, layer=18, signed_strength=16]

Checkpoint saved (explicit_test-layer18-steer_immediate-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=18 strength=8 steer_immediate (reused_existing): long=0.540 imm=0.460 fallback=0.150 logprob_margin=0.6678

steering generations:  14%|█▎        | 2700/20000 [00:01<00:15, 1093.90gen/s, dataset=explicit_test, layer=18, signed_strength=-16]

Checkpoint saved (explicit_test-layer18-steer_long_term-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=18 strength=16 steer_long_term (reused_existing): long=0.830 imm=0.170 fallback=0.130 logprob_margin=0.7582

steering generations:  14%|█▍        | 2900/20000 [00:02<00:17, 1002.33gen/s, dataset=explicit_test, layer=18, signed_strength=32]

Checkpoint saved (explicit_test-layer18-steer_immediate-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=18 strength=16 steer_immediate (reused_existing): long=0.400 imm=0.600 fallback=0.160 logprob_margin=0.6198

steering generations:  14%|█▍        | 2900/20000 [00:02<00:17, 1002.33gen/s, dataset=explicit_test, layer=18, signed_strength=-32]

Checkpoint saved (explicit_test-layer18-steer_long_term-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=18 strength=32 steer_long_term (reused_existing): long=0.830 imm=0.170 fallback=0.140 logprob_margin=0.8726

steering generations:  16%|█▌        | 3100/20000 [00:02<00:17, 947.21gen/s, dataset=explicit_test, layer=22, signed_strength=2]

Checkpoint saved (explicit_test-layer18-steer_immediate-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=18 strength=32 steer_immediate (reused_existing): long=0.340 imm=0.660 fallback=0.140 logprob_margin=0.4968

steering generations:  16%|█▌        | 3200/20000 [00:02<00:18, 928.64gen/s, dataset=explicit_test, layer=22, signed_strength=-2]

Checkpoint saved (explicit_test-layer22-steer_long_term-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=22 strength=2 steer_long_term (reused_existing): long=0.670 imm=0.330 fallback=0.140 logprob_margin=0.7112

steering generations:  16%|█▋        | 3300/20000 [00:02<00:18, 906.07gen/s, dataset=explicit_test, layer=22, signed_strength=4]

Checkpoint saved (explicit_test-layer22-steer_immediate-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=22 strength=2 steer_immediate (reused_existing): long=0.630 imm=0.370 fallback=0.180 logprob_margin=0.6668

steering generations:  17%|█▋        | 3400/20000 [00:02<00:18, 882.70gen/s, dataset=explicit_test, layer=22, signed_strength=-4]

Checkpoint saved (explicit_test-layer22-steer_long_term-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=22 strength=4 steer_long_term (reused_existing): long=0.660 imm=0.340 fallback=0.150 logprob_margin=0.7321

steering generations:  18%|█▊        | 3500/20000 [00:02<00:19, 857.78gen/s, dataset=explicit_test, layer=22, signed_strength=8]

Checkpoint saved (explicit_test-layer22-steer_immediate-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=22 strength=4 steer_immediate (reused_existing): long=0.630 imm=0.370 fallback=0.170 logprob_margin=0.6429

steering generations:  18%|█▊        | 3600/20000 [00:02<00:19, 833.54gen/s, dataset=explicit_test, layer=22, signed_strength=-8]

Checkpoint saved (explicit_test-layer22-steer_long_term-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=22 strength=8 steer_long_term (reused_existing): long=0.700 imm=0.300 fallback=0.160 logprob_margin=0.7725

steering generations:  18%|█▊        | 3700/20000 [00:03<00:20, 809.94gen/s, dataset=explicit_test, layer=22, signed_strength=16]

Checkpoint saved (explicit_test-layer22-steer_immediate-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=22 strength=8 steer_immediate (reused_existing): long=0.570 imm=0.430 fallback=0.170 logprob_margin=0.5903

steering generations:  19%|█▉        | 3800/20000 [00:03<00:20, 788.48gen/s, dataset=explicit_test, layer=22, signed_strength=-16]

Checkpoint saved (explicit_test-layer22-steer_long_term-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=22 strength=16 steer_long_term (reused_existing): long=0.740 imm=0.260 fallback=0.160 logprob_margin=0.8562

steering generations:  20%|█▉        | 3900/20000 [00:03<00:20, 768.17gen/s, dataset=explicit_test, layer=22, signed_strength=32]

Checkpoint saved (explicit_test-layer22-steer_immediate-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=22 strength=16 steer_immediate (reused_existing): long=0.470 imm=0.530 fallback=0.210 logprob_margin=0.4562

steering generations:  20%|██        | 4000/20000 [00:03<00:21, 749.75gen/s, dataset=explicit_test, layer=22, signed_strength=-32]

Checkpoint saved (explicit_test-layer22-steer_long_term-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=22 strength=32 steer_long_term (reused_existing): long=0.790 imm=0.210 fallback=0.140 logprob_margin=1.0575

steering generations:  20%|██        | 4100/20000 [00:03<00:21, 730.13gen/s, dataset=explicit_test, layer=26, signed_strength=2]

Checkpoint saved (explicit_test-layer22-steer_immediate-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=22 strength=32 steer_immediate (reused_existing): long=0.340 imm=0.660 fallback=0.250 logprob_margin=-0.0275

steering generations:  21%|██        | 4200/20000 [00:03<00:22, 710.40gen/s, dataset=explicit_test, layer=26, signed_strength=-2]

Checkpoint saved (explicit_test-layer26-steer_long_term-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=26 strength=2 steer_long_term (reused_existing): long=0.640 imm=0.360 fallback=0.160 logprob_margin=0.7126

steering generations:  22%|██▏       | 4300/20000 [00:03<00:22, 696.20gen/s, dataset=explicit_test, layer=26, signed_strength=4]

Checkpoint saved (explicit_test-layer26-steer_immediate-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=26 strength=2 steer_immediate (reused_existing): long=0.630 imm=0.370 fallback=0.180 logprob_margin=0.6662

steering generations:  22%|██▏       | 4400/20000 [00:04<00:22, 681.94gen/s, dataset=explicit_test, layer=26, signed_strength=-4]

Checkpoint saved (explicit_test-layer26-steer_long_term-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=26 strength=4 steer_long_term (reused_existing): long=0.650 imm=0.350 fallback=0.160 logprob_margin=0.7354

steering generations:  22%|██▎       | 4500/20000 [00:04<00:23, 666.88gen/s, dataset=explicit_test, layer=26, signed_strength=8]

Checkpoint saved (explicit_test-layer26-steer_immediate-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=26 strength=4 steer_immediate (reused_existing): long=0.620 imm=0.380 fallback=0.190 logprob_margin=0.6420

steering generations:  23%|██▎       | 4600/20000 [00:04<00:23, 654.42gen/s, dataset=explicit_test, layer=26, signed_strength=-8]

Checkpoint saved (explicit_test-layer26-steer_long_term-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=26 strength=8 steer_long_term (reused_existing): long=0.660 imm=0.340 fallback=0.170 logprob_margin=0.7810

steering generations:  24%|██▎       | 4700/20000 [00:04<00:23, 642.73gen/s, dataset=explicit_test, layer=26, signed_strength=16]

Checkpoint saved (explicit_test-layer26-steer_immediate-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=26 strength=8 steer_immediate (reused_existing): long=0.640 imm=0.360 fallback=0.190 logprob_margin=0.5936

steering generations:  24%|██▍       | 4800/20000 [00:04<00:24, 630.29gen/s, dataset=explicit_test, layer=26, signed_strength=-16]

Checkpoint saved (explicit_test-layer26-steer_long_term-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=26 strength=16 steer_long_term (reused_existing): long=0.670 imm=0.330 fallback=0.190 logprob_margin=0.8700

steering generations:  24%|██▍       | 4900/20000 [00:04<00:24, 620.14gen/s, dataset=explicit_test, layer=26, signed_strength=32]

Checkpoint saved (explicit_test-layer26-steer_immediate-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=26 strength=16 steer_immediate (reused_existing): long=0.650 imm=0.350 fallback=0.160 logprob_margin=0.4905

steering generations:  25%|██▌       | 5000/20000 [00:05<00:24, 609.20gen/s, dataset=explicit_test, layer=26, signed_strength=-32]

Checkpoint saved (explicit_test-layer26-steer_long_term-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=26 strength=32 steer_long_term (reused_existing): long=0.660 imm=0.340 fallback=0.180 logprob_margin=1.0462

steering generations:  26%|██▋       | 5300/20000 [00:05<00:15, 953.54gen/s, dataset=implicit_full, layer=10, signed_strength=2]

Checkpoint saved (explicit_test-layer26-steer_immediate-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[explicit_test] mm layer=26 strength=32 steer_immediate (reused_existing): long=0.600 imm=0.400 fallback=0.190 logprob_margin=0.2602

steering generations:  28%|██▊       | 5600/20000 [00:05<00:12, 1149.35gen/s, dataset=implicit_full, layer=10, signed_strength=-2]

Checkpoint saved (implicit_full-layer10-steer_long_term-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=10 strength=2 steer_long_term (reused_existing): long=0.600 imm=0.400 fallback=0.077 logprob_margin=0.2007

steering generations:  28%|██▊       | 5600/20000 [00:05<00:12, 1149.35gen/s, dataset=implicit_full, layer=10, signed_strength=4]

Checkpoint saved (implicit_full-layer10-steer_immediate-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=10 strength=2 steer_immediate (reused_existing): long=0.587 imm=0.413 fallback=0.077 logprob_margin=0.1971

steering generations:  31%|███       | 6200/20000 [00:05<00:10, 1309.19gen/s, dataset=implicit_full, layer=10, signed_strength=-4]

Checkpoint saved (implicit_full-layer10-steer_long_term-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=10 strength=4 steer_long_term (reused_existing): long=0.600 imm=0.400 fallback=0.080 logprob_margin=0.2066

steering generations:  32%|███▎      | 6500/20000 [00:06<00:10, 1327.62gen/s, dataset=implicit_full, layer=10, signed_strength=8]

Checkpoint saved (implicit_full-layer10-steer_immediate-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=10 strength=4 steer_immediate (reused_existing): long=0.577 imm=0.423 fallback=0.073 logprob_margin=0.1984

steering generations:  32%|███▎      | 6500/20000 [00:06<00:10, 1327.62gen/s, dataset=implicit_full, layer=10, signed_strength=-8]The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Checkpoint saved (implicit_full-layer10-steer_long_term-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=10 strength=8 steer_long_term (reused_existing): long=0.603 imm=0.397 fallback=0.080 logprob_margin=0.2240

steering generations:  34%|███▍      | 6800/20000 [06:26<4:33:34,  1.24s/gen, dataset=implicit_full, layer=10, signed_strength=16]

Checkpoint saved (implicit_full-layer10-steer_immediate-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=10 strength=8 steer_immediate (computed_now): long=0.557 imm=0.443 fallback=0.053 logprob_margin=0.2041

steering generations:  36%|███▌      | 7100/20000 [12:32<4:23:25,  1.23s/gen, dataset=implicit_full, layer=10, signed_strength=-16]

Checkpoint saved (implicit_full-layer10-steer_long_term-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=10 strength=16 steer_long_term (computed_now): long=0.630 imm=0.370 fallback=0.100 logprob_margin=0.2582

steering generations:  37%|███▋      | 7400/20000 [18:51<4:32:15,  1.30s/gen, dataset=implicit_full, layer=10, signed_strength=32]

Checkpoint saved (implicit_full-layer10-steer_immediate-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=10 strength=16 steer_immediate (computed_now): long=0.550 imm=0.450 fallback=0.050 logprob_margin=0.2344

steering generations:  38%|███▊      | 7700/20000 [25:20<4:29:14,  1.31s/gen, dataset=implicit_full, layer=10, signed_strength=-32]

Checkpoint saved (implicit_full-layer10-steer_long_term-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=10 strength=32 steer_long_term (computed_now): long=0.603 imm=0.397 fallback=0.563 logprob_margin=0.2438

steering generations:  40%|████      | 8000/20000 [31:48<4:20:45,  1.30s/gen, dataset=implicit_full, layer=14, signed_strength=2]

Checkpoint saved (implicit_full-layer10-steer_immediate-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=10 strength=32 steer_immediate (computed_now): long=0.577 imm=0.423 fallback=0.137 logprob_margin=0.2750

steering generations:  42%|████▏     | 8300/20000 [38:05<4:05:26,  1.26s/gen, dataset=implicit_full, layer=14, signed_strength=-2]

Checkpoint saved (implicit_full-layer14-steer_long_term-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=14 strength=2 steer_long_term (computed_now): long=0.597 imm=0.403 fallback=0.087 logprob_margin=0.1995

steering generations:  43%|████▎     | 8600/20000 [44:30<4:11:03,  1.32s/gen, dataset=implicit_full, layer=14, signed_strength=4]

Checkpoint saved (implicit_full-layer14-steer_immediate-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=14 strength=2 steer_immediate (computed_now): long=0.590 imm=0.410 fallback=0.080 logprob_margin=0.1974

steering generations:  44%|████▍     | 8900/20000 [51:00<3:55:36,  1.27s/gen, dataset=implicit_full, layer=14, signed_strength=-4]

Checkpoint saved (implicit_full-layer14-steer_long_term-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=14 strength=4 steer_long_term (computed_now): long=0.613 imm=0.387 fallback=0.070 logprob_margin=0.2031

steering generations:  46%|████▌     | 9200/20000 [57:19<3:44:17,  1.25s/gen, dataset=implicit_full, layer=14, signed_strength=8]

Checkpoint saved (implicit_full-layer14-steer_immediate-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=14 strength=4 steer_immediate (computed_now): long=0.577 imm=0.423 fallback=0.070 logprob_margin=0.1981

steering generations:  48%|████▊     | 9500/20000 [1:03:42<3:41:28,  1.27s/gen, dataset=implicit_full, layer=14, signed_strength=-8]

Checkpoint saved (implicit_full-layer14-steer_long_term-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=14 strength=8 steer_long_term (computed_now): long=0.637 imm=0.363 fallback=0.097 logprob_margin=0.2162

steering generations:  49%|████▉     | 9800/20000 [1:10:02<3:42:04,  1.31s/gen, dataset=implicit_full, layer=14, signed_strength=16]

Checkpoint saved (implicit_full-layer14-steer_immediate-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=14 strength=8 steer_immediate (computed_now): long=0.563 imm=0.437 fallback=0.050 logprob_margin=0.2021

steering generations:  50%|█████     | 10100/20000 [1:16:31<3:33:54,  1.30s/gen, dataset=implicit_full, layer=14, signed_strength=-16]

Checkpoint saved (implicit_full-layer14-steer_long_term-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=14 strength=16 steer_long_term (computed_now): long=0.663 imm=0.337 fallback=0.143 logprob_margin=0.2812

steering generations:  52%|█████▏    | 10400/20000 [1:23:03<3:33:33,  1.33s/gen, dataset=implicit_full, layer=14, signed_strength=32]

Checkpoint saved (implicit_full-layer14-steer_immediate-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=14 strength=16 steer_immediate (computed_now): long=0.520 imm=0.480 fallback=0.030 logprob_margin=0.2401

steering generations:  54%|█████▎    | 10700/20000 [1:29:39<3:21:51,  1.30s/gen, dataset=implicit_full, layer=14, signed_strength=-32]

Checkpoint saved (implicit_full-layer14-steer_long_term-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=14 strength=32 steer_long_term (computed_now): long=0.653 imm=0.347 fallback=0.633 logprob_margin=0.3066

steering generations:  55%|█████▌    | 11000/20000 [1:36:14<3:16:02,  1.31s/gen, dataset=implicit_full, layer=18, signed_strength=2]

Checkpoint saved (implicit_full-layer14-steer_immediate-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=14 strength=32 steer_immediate (computed_now): long=0.520 imm=0.480 fallback=0.630 logprob_margin=0.4307

steering generations:  56%|█████▋    | 11300/20000 [1:42:35<3:02:36,  1.26s/gen, dataset=implicit_full, layer=18, signed_strength=-2]

Checkpoint saved (implicit_full-layer18-steer_long_term-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=18 strength=2 steer_long_term (computed_now): long=0.603 imm=0.397 fallback=0.087 logprob_margin=0.2013

steering generations:  58%|█████▊    | 11600/20000 [1:48:56<2:56:30,  1.26s/gen, dataset=implicit_full, layer=18, signed_strength=4]

Checkpoint saved (implicit_full-layer18-steer_immediate-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=18 strength=2 steer_immediate (computed_now): long=0.577 imm=0.423 fallback=0.087 logprob_margin=0.1946

steering generations:  60%|█████▉    | 11900/20000 [1:55:11<2:47:36,  1.24s/gen, dataset=implicit_full, layer=18, signed_strength=-4]

Checkpoint saved (implicit_full-layer18-steer_long_term-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=18 strength=4 steer_long_term (computed_now): long=0.627 imm=0.373 fallback=0.080 logprob_margin=0.2047

steering generations:  61%|██████    | 12200/20000 [2:01:24<2:40:32,  1.23s/gen, dataset=implicit_full, layer=18, signed_strength=8]

Checkpoint saved (implicit_full-layer18-steer_immediate-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=18 strength=4 steer_immediate (computed_now): long=0.560 imm=0.440 fallback=0.077 logprob_margin=0.1911

steering generations:  62%|██████▎   | 12500/20000 [2:07:42<2:36:13,  1.25s/gen, dataset=implicit_full, layer=18, signed_strength=-8]

Checkpoint saved (implicit_full-layer18-steer_long_term-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=18 strength=8 steer_long_term (computed_now): long=0.697 imm=0.303 fallback=0.060 logprob_margin=0.2110

steering generations:  64%|██████▍   | 12800/20000 [2:14:02<2:33:35,  1.28s/gen, dataset=implicit_full, layer=18, signed_strength=16]

Checkpoint saved (implicit_full-layer18-steer_immediate-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=18 strength=8 steer_immediate (computed_now): long=0.530 imm=0.470 fallback=0.073 logprob_margin=0.1850

steering generations:  66%|██████▌   | 13100/20000 [2:20:23<2:25:28,  1.27s/gen, dataset=implicit_full, layer=18, signed_strength=-16]

Checkpoint saved (implicit_full-layer18-steer_long_term-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=18 strength=16 steer_long_term (computed_now): long=0.763 imm=0.237 fallback=0.033 logprob_margin=0.2222

steering generations:  67%|██████▋   | 13400/20000 [2:26:54<2:26:11,  1.33s/gen, dataset=implicit_full, layer=18, signed_strength=32]

Checkpoint saved (implicit_full-layer18-steer_immediate-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=18 strength=16 steer_immediate (computed_now): long=0.447 imm=0.553 fallback=0.063 logprob_margin=0.1743

steering generations:  68%|██████▊   | 13700/20000 [2:33:14<2:07:58,  1.22s/gen, dataset=implicit_full, layer=18, signed_strength=-32]

Checkpoint saved (implicit_full-layer18-steer_long_term-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=18 strength=32 steer_long_term (computed_now): long=0.820 imm=0.180 fallback=0.057 logprob_margin=0.2371

steering generations:  70%|███████   | 14000/20000 [2:39:39<2:09:30,  1.30s/gen, dataset=implicit_full, layer=22, signed_strength=2]

Checkpoint saved (implicit_full-layer18-steer_immediate-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=18 strength=32 steer_immediate (computed_now): long=0.350 imm=0.650 fallback=0.070 logprob_margin=0.1933

steering generations:  72%|███████▏  | 14300/20000 [2:46:00<1:58:38,  1.25s/gen, dataset=implicit_full, layer=22, signed_strength=-2]

Checkpoint saved (implicit_full-layer22-steer_long_term-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=22 strength=2 steer_long_term (computed_now): long=0.597 imm=0.403 fallback=0.073 logprob_margin=0.2054

steering generations:  73%|███████▎  | 14600/20000 [2:52:21<1:53:30,  1.26s/gen, dataset=implicit_full, layer=22, signed_strength=4]

Checkpoint saved (implicit_full-layer22-steer_immediate-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=22 strength=2 steer_immediate (computed_now): long=0.587 imm=0.413 fallback=0.087 logprob_margin=0.1895

steering generations:  74%|███████▍  | 14900/20000 [2:58:44<1:49:09,  1.28s/gen, dataset=implicit_full, layer=22, signed_strength=-4]

Checkpoint saved (implicit_full-layer22-steer_long_term-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=22 strength=4 steer_long_term (computed_now): long=0.603 imm=0.397 fallback=0.083 logprob_margin=0.2122

steering generations:  76%|███████▌  | 15200/20000 [3:05:19<1:43:46,  1.30s/gen, dataset=implicit_full, layer=22, signed_strength=8]

Checkpoint saved (implicit_full-layer22-steer_immediate-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=22 strength=4 steer_immediate (computed_now): long=0.567 imm=0.433 fallback=0.080 logprob_margin=0.1800

steering generations:  78%|███████▊  | 15500/20000 [3:11:37<1:36:03,  1.28s/gen, dataset=implicit_full, layer=22, signed_strength=-8]

Checkpoint saved (implicit_full-layer22-steer_long_term-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=22 strength=8 steer_long_term (computed_now): long=0.640 imm=0.360 fallback=0.063 logprob_margin=0.2238

steering generations:  79%|███████▉  | 15800/20000 [3:18:03<1:29:57,  1.29s/gen, dataset=implicit_full, layer=22, signed_strength=16]

Checkpoint saved (implicit_full-layer22-steer_immediate-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=22 strength=8 steer_immediate (computed_now): long=0.547 imm=0.453 fallback=0.097 logprob_margin=0.1574

steering generations:  80%|████████  | 16100/20000 [3:24:28<1:22:28,  1.27s/gen, dataset=implicit_full, layer=22, signed_strength=-16]

Checkpoint saved (implicit_full-layer22-steer_long_term-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=22 strength=16 steer_long_term (computed_now): long=0.697 imm=0.303 fallback=0.060 logprob_margin=0.2415

steering generations:  82%|████████▏ | 16400/20000 [3:31:04<1:18:19,  1.31s/gen, dataset=implicit_full, layer=22, signed_strength=32]

Checkpoint saved (implicit_full-layer22-steer_immediate-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=22 strength=16 steer_immediate (computed_now): long=0.507 imm=0.493 fallback=0.113 logprob_margin=0.0954

steering generations:  84%|████████▎ | 16700/20000 [3:37:36<1:11:44,  1.30s/gen, dataset=implicit_full, layer=22, signed_strength=-32]

Checkpoint saved (implicit_full-layer22-steer_long_term-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=22 strength=32 steer_long_term (computed_now): long=0.667 imm=0.333 fallback=0.177 logprob_margin=0.2690

steering generations:  85%|████████▌ | 17000/20000 [3:44:10<1:06:00,  1.32s/gen, dataset=implicit_full, layer=26, signed_strength=2]

Checkpoint saved (implicit_full-layer22-steer_immediate-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=22 strength=32 steer_immediate (computed_now): long=0.497 imm=0.503 fallback=0.277 logprob_margin=-0.1235

steering generations:  86%|████████▋ | 17300/20000 [3:50:31<57:00,  1.27s/gen, dataset=implicit_full, layer=26, signed_strength=-2]

Checkpoint saved (implicit_full-layer26-steer_long_term-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=26 strength=2 steer_long_term (computed_now): long=0.587 imm=0.413 fallback=0.073 logprob_margin=0.2084

steering generations:  88%|████████▊ | 17600/20000 [3:56:54<50:13,  1.26s/gen, dataset=implicit_full, layer=26, signed_strength=4]

Checkpoint saved (implicit_full-layer26-steer_immediate-2): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=26 strength=2 steer_immediate (computed_now): long=0.587 imm=0.413 fallback=0.080 logprob_margin=0.1871

steering generations:  90%|████████▉ | 17900/20000 [4:03:16<45:19,  1.30s/gen, dataset=implicit_full, layer=26, signed_strength=-4]

Checkpoint saved (implicit_full-layer26-steer_long_term-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=26 strength=4 steer_long_term (computed_now): long=0.583 imm=0.417 fallback=0.073 logprob_margin=0.2186

steering generations:  91%|█████████ | 18200/20000 [4:09:46<39:32,  1.32s/gen, dataset=implicit_full, layer=26, signed_strength=8]

Checkpoint saved (implicit_full-layer26-steer_immediate-4): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=26 strength=4 steer_immediate (computed_now): long=0.583 imm=0.417 fallback=0.087 logprob_margin=0.1760

steering generations:  92%|█████████▎| 18500/20000 [4:16:15<33:03,  1.32s/gen, dataset=implicit_full, layer=26, signed_strength=-8]

Checkpoint saved (implicit_full-layer26-steer_long_term-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=26 strength=8 steer_long_term (computed_now): long=0.597 imm=0.403 fallback=0.073 logprob_margin=0.2385

steering generations:  94%|█████████▍| 18800/20000 [4:22:45<25:09,  1.26s/gen, dataset=implicit_full, layer=26, signed_strength=16]

Checkpoint saved (implicit_full-layer26-steer_immediate-8): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=26 strength=8 steer_immediate (computed_now): long=0.577 imm=0.423 fallback=0.093 logprob_margin=0.1529

steering generations:  96%|█████████▌| 19100/20000 [4:29:11<19:34,  1.31s/gen, dataset=implicit_full, layer=26, signed_strength=-16]

Checkpoint saved (implicit_full-layer26-steer_long_term-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=26 strength=16 steer_long_term (computed_now): long=0.613 imm=0.387 fallback=0.057 logprob_margin=0.2761

steering generations:  97%|█████████▋| 19400/20000 [4:35:38<12:36,  1.26s/gen, dataset=implicit_full, layer=26, signed_strength=32]

Checkpoint saved (implicit_full-layer26-steer_immediate-16): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=26 strength=16 steer_immediate (computed_now): long=0.580 imm=0.420 fallback=0.087 logprob_margin=0.1027

steering generations:  98%|█████████▊| 19700/20000 [4:42:02<06:21,  1.27s/gen, dataset=implicit_full, layer=26, signed_strength=-32]

Checkpoint saved (implicit_full-layer26-steer_long_term-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=26 strength=32 steer_long_term (computed_now): long=0.637 imm=0.363 fallback=0.047 logprob_margin=0.3479

steering generations: 100%|██████████| 20000/20000 [4:48:29<00:00,  1.16gen/s, dataset=implicit_full, layer=26, signed_strength=-32]

Checkpoint saved (implicit_full-layer26-steer_immediate-32): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
[implicit_full] mm layer=26 strength=32 steer_immediate (computed_now): long=0.557 imm=0.443 fallback=0.093 logprob_margin=-0.0117
Steering generation time (min): 288.5

Checkpoint saved (final): /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
Saved summary    : /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_summary_20260406-121506.csv
Saved logs       : /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_logs_20260406-121506.csv
Saved probe slice: /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_probe_slice_20260406-121506.csv
Saved reuse map  : /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_reuse_coverage_20260406-121506.csv
Saved config     : /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_config_20260406-121506.json
Saved artifacts  : /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506/mmraz_qwen3_probe_artifact_steering_question_options_answer_artifacts_20260406-121506.csv
Output dir       : /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506

In [4]:
print('Output dir:', result['output_dir'])
display(result['probe_slice_df'])
display(result['baseline_summary_df'])
display(result['reuse_coverage_df'])
display(result['artifact_index_df'])

Output dir: /workspace/results/qwen3_4b_probe_artifact_steering_question_options_answer_vast/20260406-121506

,train_regime,feature_name,vector_key,layer,raw_norm,steering_norm
0,explicit_train_only,mean_answer_tokens,mm_steering_vectors,10,8.771654,1.0
1,explicit_train_only,mean_answer_tokens,mm_steering_vectors,14,10.132462,1.0
2,explicit_train_only,mean_answer_tokens,mm_steering_vectors,18,11.991506,1.0
3,explicit_train_only,mean_answer_tokens,mm_steering_vectors,22,20.724382,1.0
4,explicit_train_only,mean_answer_tokens,mm_steering_vectors,26,33.307693,1.0

,dataset,probe_variant,condition,layer,strength,signed_strength,raw_vector_norm,steering_vector_norm,baseline_prop_choose_long_term,baseline_prop_choose_immediate,...,n_no_fallback_prompts,prop_choose_long_term,prop_choose_immediate,prop_choose_long_term_no_fallback,prop_choose_immediate_no_fallback,fallback_rate,direct_parse_rate,mean_long_minus_immediate_avg_logprob,mean_long_minus_immediate_sum_logprob,prop_logprob_prefers_long_term
0,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,0.640000,0.360000,...,85,0.640000,0.360000,0.705882,0.294118,0.15,0.85,0.689644,0.381820,0.57
1,implicit_full,baseline,baseline,-1,0.0,0.0,NaN,NaN,0.586667,0.413333,...,276,0.586667,0.413333,0.605072,0.394928,0.08,0.92,0.197873,0.858146,0.60

,dataset,condition,layer,strength,signed_strength,n_prompts,reused,source_path
0,explicit_test,baseline,-1,0.0,0.0,100,True,/workspace/results/qwen3_4b_probe_artifact_ste...
1,explicit_test,steer_long_term,10,2.0,2.0,100,True,/workspace/results/qwen3_4b_probe_artifact_ste...
2,explicit_test,steer_immediate,10,2.0,-2.0,100,True,/workspace/results/qwen3_4b_probe_artifact_ste...
3,explicit_test,steer_long_term,10,4.0,4.0,100,True,/workspace/results/qwen3_4b_probe_artifact_ste...
4,explicit_test,steer_immediate,10,4.0,-4.0,100,True,/workspace/results/qwen3_4b_probe_artifact_ste...
...,...,...,...,...,...,...,...,...
97,implicit_full,steer_immediate,26,8.0,-8.0,300,False,NaN
98,implicit_full,steer_long_term,26,16.0,16.0,300,False,NaN
99,implicit_full,steer_immediate,26,16.0,-16.0,300,False,NaN
100,implicit_full,steer_long_term,26,32.0,32.0,300,False,NaN
101,implicit_full,steer_immediate,26,32.0,-32.0,300,False,NaN

,artifact,path
0,summary_csv,/workspace/results/qwen3_4b_probe_artifact_ste...
1,logs_csv,/workspace/results/qwen3_4b_probe_artifact_ste...
2,probe_slice_csv,/workspace/results/qwen3_4b_probe_artifact_ste...
3,reuse_coverage_csv,/workspace/results/qwen3_4b_probe_artifact_ste...
4,config_json,/workspace/results/qwen3_4b_probe_artifact_ste...
5,explicit_test_heatmap_png,/workspace/results/qwen3_4b_probe_artifact_ste...
6,implicit_full_heatmap_png,/workspace/results/qwen3_4b_probe_artifact_ste...

In [5]:
result['summary_df'].head(20)

,dataset,probe_variant,condition,layer,strength,signed_strength,raw_vector_norm,steering_vector_norm,baseline_prop_choose_long_term,baseline_prop_choose_immediate,...,n_no_fallback_prompts,prop_choose_long_term,prop_choose_immediate,prop_choose_long_term_no_fallback,prop_choose_immediate_no_fallback,fallback_rate,direct_parse_rate,mean_long_minus_immediate_avg_logprob,mean_long_minus_immediate_sum_logprob,prop_logprob_prefers_long_term
0,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,0.640000,0.360000,...,85,0.640000,0.360000,0.705882,0.294118,0.15,0.85,0.689644,0.381820,0.57
1,implicit_full,baseline,baseline,-1,0.0,0.0,NaN,NaN,0.586667,0.413333,...,276,0.586667,0.413333,0.605072,0.394928,0.08,0.92,0.197873,0.858146,0.60
2,explicit_test,mm,steer_long_term,10,2.0,2.0,8.771654,1.0,0.640000,0.360000,...,79,0.640000,0.360000,0.746835,0.253165,0.21,0.79,0.685718,0.378509,0.57
3,explicit_test,mm,steer_immediate,10,2.0,-2.0,8.771654,1.0,0.640000,0.360000,...,83,0.640000,0.360000,0.722892,0.277108,0.17,0.83,0.687882,0.368582,0.57
4,explicit_test,mm,steer_long_term,10,4.0,4.0,8.771654,1.0,0.640000,0.360000,...,80,0.650000,0.350000,0.762500,0.237500,0.20,0.80,0.678562,0.366785,0.57
5,explicit_test,mm,steer_immediate,10,4.0,-4.0,8.771654,1.0,0.640000,0.360000,...,81,0.630000,0.370000,0.728395,0.271605,0.19,0.81,0.678644,0.333406,0.57
6,explicit_test,mm,steer_long_term,10,8.0,8.0,8.771654,1.0,0.640000,0.360000,...,80,0.670000,0.330000,0.787500,0.212500,0.20,0.80,0.664561,0.349662,0.56
7,explicit_test,mm,steer_immediate,10,8.0,-8.0,8.771654,1.0,0.640000,0.360000,...,86,0.660000,0.340000,0.732558,0.267442,0.14,0.86,0.640643,0.204029,0.57
8,explicit_test,mm,steer_long_term,10,16.0,16.0,8.771654,1.0,0.640000,0.360000,...,77,0.710000,0.290000,0.831169,0.168831,0.23,0.77,0.658397,0.376816,0.56
9,explicit_test,mm,steer_immediate,10,16.0,-16.0,8.771654,1.0,0.640000,0.360000,...,89,0.590000,0.410000,0.640449,0.359551,0.11,0.89,0.552601,-0.068308,0.57
10,explicit_test,mm,steer_long_term,10,32.0,32.0,8.771654,1.0,0.640000,0.360000,...,39,0.640000,0.360000,0.923077,0.076923,0.61,0.39,0.903974,1.333672,0.60
11,explicit_test,mm,steer_immediate,10,32.0,-32.0,8.771654,1.0,0.640000,0.360000,...,64,0.440000,0.560000,0.390625,0.609375,0.36,0.64,0.569173,0.074536,0.57
12,explicit_test,mm,steer_long_term,14,2.0,2.0,10.132462,1.0,0.640000,0.360000,...,81,0.640000,0.360000,0.740741,0.259259,0.19,0.81,0.687157,0.374501,0.57
13,explicit_test,mm,steer_immediate,14,2.0,-2.0,10.132462,1.0,0.640000,0.360000,...,82,0.640000,0.360000,0.731707,0.268293,0.18,0.82,0.694679,0.395886,0.56
14,explicit_test,mm,steer_long_term,14,4.0,4.0,10.132462,1.0,0.640000,0.360000,...,82,0.660000,0.340000,0.756098,0.243902,0.18,0.82,0.685763,0.373730,0.57
15,explicit_test,mm,steer_immediate,14,4.0,-4.0,10.132462,1.0,0.640000,0.360000,...,82,0.640000,0.360000,0.731707,0.268293,0.18,0.82,0.700925,0.415059,0.57
16,explicit_test,mm,steer_long_term,14,8.0,8.0,10.132462,1.0,0.640000,0.360000,...,79,0.680000,0.320000,0.810127,0.189873,0.21,0.79,0.695374,0.415083,0.57
17,explicit_test,mm,steer_immediate,14,8.0,-8.0,10.132462,1.0,0.640000,0.360000,...,83,0.580000,0.420000,0.650602,0.349398,0.17,0.83,0.715116,0.463149,0.57
18,explicit_test,mm,steer_long_term,14,16.0,16.0,10.132462,1.0,0.640000,0.360000,...,79,0.700000,0.300000,0.810127,0.189873,0.21,0.79,0.745889,0.642238,0.57
19,explicit_test,mm,steer_immediate,14,16.0,-16.0,10.132462,1.0,0.640000,0.360000,...,93,0.540000,0.460000,0.569892,0.430108,0.07,0.93,0.727687,0.495392,0.57

In [6]:
result['logs_df'].head(20)

,dataset,probe_variant,condition,layer,strength,signed_strength,raw_vector_norm,steering_vector_norm,prompt_idx,question,...,immediate_token_count,long_term_sum_logprob,long_term_avg_logprob,long_term_token_count,long_minus_immediate_sum_logprob,long_minus_immediate_avg_logprob,logprob_prefers_long_term,source_path,result_source,reused_from_path
0,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,0,"When developing a roadmap for this initiative,...",...,11,-38.766693,-4.307410,9,-12.421978,-1.912436,0.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
1,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,1,"When setting milestones, focus on:",...,7,-39.382812,-6.563802,6,0.335938,-0.889695,0.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
2,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,2,"When drafting the plan, consider:",...,7,-21.468710,-3.578118,6,8.308702,0.675798,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
3,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,3,Resource planning aligns with:,...,5,-31.069576,-6.213915,5,2.868950,0.573790,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
4,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,4,Contingency planning addresses:,...,8,-31.743282,-3.967910,8,0.028427,0.003553,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
5,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,5,The planning framework emphasizes:,...,7,-36.132820,-4.516603,8,7.093742,1.658621,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
6,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,6,Choose the option that delivers:,...,7,-37.531563,-5.361652,7,8.218750,1.174108,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
7,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,7,"When faced with uncertainty, choose:",...,6,-31.235968,-5.205995,6,6.468748,1.078125,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
8,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,8,The decision tree evaluates:,...,6,-40.843750,-8.168750,5,-0.078125,-1.374479,0.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
9,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,9,Decision reversibility matters over:,...,4,-23.625557,-5.906389,4,18.500000,4.625000,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
10,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,10,The debugging effort addresses:,...,6,-36.093838,-5.156263,7,4.632732,1.631499,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
11,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,11,The solution scope addresses:,...,5,-29.235891,-5.847178,5,0.921871,0.184374,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
12,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,12,The return timeline spans:,...,3,-42.535156,-14.178386,3,1.457634,0.485878,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
13,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,13,Investment evaluation uses:,...,4,-29.698545,-5.939709,5,6.113245,3.013238,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
14,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,14,"When timing investments, focus on:",...,5,-34.984402,-6.996881,5,-5.882650,-1.176530,0.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
15,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,15,Reinvestment decisions consider:,...,4,-28.234381,-5.646876,5,5.171877,2.704688,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
16,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,16,The allocation strategy serves:,...,5,-40.929688,-10.232422,4,-13.052505,-4.656985,0.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
17,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,17,Risk tolerance reflects:,...,4,-34.187229,-8.546807,4,6.060551,1.515138,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
18,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,18,The asset selection criteria includes:,...,5,-37.235092,-7.447019,5,5.113361,1.022673,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...
19,explicit_test,baseline,baseline,-1,0.0,0.0,NaN,NaN,19,Investment success is measured over:,...,3,-28.820971,-7.205243,4,4.605635,3.936960,1.0,/workspace/results/qwen3_4b_probe_artifact_ste...,reused_existing,/workspace/results/qwen3_4b_probe_artifact_ste...